mail:
  imap:
    ssl: true
    host: "imap-endpoint"
    port: 993
    username: "change"
    password: "it"
io:
  arcmail:
    basePath: "basePath"

spring:
  datasource:
    url: "jdbc:h2:file:./db/ArcMai"
    driver-class-name: org.h2.Driver
