mail:
  imap:
    ssl: true
    host: imap.gmail.com
    port: 993
    username: "change"
    password: "it"

# Task execution
spring:
  task:
    execution:
      thread-name-prefix: autohost-task-
      pool:
        core-size: 2
        max-size: 200
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: mail-receiver-
      pool:
        size: 2